# Generated by Django 4.2.16 on 2025-02-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Procedure', '0030_remove_services_commission_percentage'),
        ('Attendanceapp', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission_Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendanceapp.employee')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.services')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_datetime', models.DateTimeField(blank=True, null=True)),
                ('amount_commission', models.FloatField()),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.invoice_det')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Attendanceapp.employee')),
            ],
        ),
    ]
