# Generated by Django 4.2.16 on 2025-03-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission_percent',
            old_name='percent',
            new_name='commission_percentage',
        ),
    ]
