# Generated by Django 4.2.16 on 2025-03-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0003_alter_employee_user'),
        ('Accounting', '0002_rename_percent_commission_percent_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission_percent',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Attendanceapp.employee'),
        ),
    ]
