# Generated by Django 4.2.16 on 2025-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0003_alter_employee_user'),
        ('Procedure', '0030_remove_services_commission_percentage'),
        ('Accounting', '0003_alter_commission_percent_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commission_Percent',
            new_name='Commission_Value',
        ),
        migrations.RenameField(
            model_name='commission_value',
            old_name='commission_percentage',
            new_name='commission_value',
        ),
    ]
