# Generated by Django 4.2.16 on 2025-03-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0003_alter_employee_user'),
        ('Accounting', '0004_rename_commission_percent_commission_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Attendanceapp.employee'),
        ),
    ]
