# Generated by Django 4.2.16 on 2025-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_alter_commission_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='amount_commission',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
