# Generated by Django 4.2.16 on 2025-03-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_alter_commission_amount_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
