# Generated by Django 4.2.16 on 2025-03-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0003_alter_employee_user'),
        ('Accounting', '0007_alter_commission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission_value',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Attendanceapp.employee'),
        ),
    ]
