# Generated by Django 3.2.15 on 2022-10-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_log',
            old_name='send',
            new_name='sent',
        ),
    ]
