# Generated by Django 3.2.15 on 2022-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0002_rename_send_email_log_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='last_used',
            field=models.BooleanField(default=False),
        ),
    ]
