# Generated by Django 3.2.15 on 2022-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0003_cards_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.CharField(default='Active', max_length=45),
        ),
    ]
