# Generated by Django 3.2.15 on 2022-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0004_alter_cards_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='ct_password',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='ct_user',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='CONNECTICUT'),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='ct_password',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='ct_user',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='CONNECTICUT'),
        ),
    ]
