# Generated by Django 3.2.15 on 2023-02-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0005_auto_20221213_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ct_user',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Connecticut'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cusnum',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Customer #'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='floridaid',
            field=models.CharField(choices=[('Local', 'Local'), ('Auto', 'Auto'), ('Inter-State', 'Inter-State'), ('Taxes', 'Taxes')], default='--Select--', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='prepass',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='prepass_password',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='prepassreg',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='ct_user',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Connecticut'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='cusnum',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Customer #'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='floridaid',
            field=models.CharField(choices=[('Local', 'Local'), ('Auto', 'Auto'), ('Inter-State', 'Inter-State'), ('Taxes', 'Taxes')], default='--Select--', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='prepass',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='prepass_password',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='prepassreg',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Prepass'),
        ),
    ]
