# Generated by Django 3.2.15 on 2023-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0006_auto_20230203_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='floridaid',
            field=models.CharField(default='--Select--', max_length=20, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='floridaid',
            field=models.CharField(default='--Select--', max_length=20, verbose_name='Client Type'),
        ),
    ]
