# Generated by Django 3.2.15 on 2023-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0007_auto_20230203_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='method',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery Method'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='method',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery Method'),
        ),
    ]
