# Generated by Django 3.2.15 on 2023-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0008_auto_20230206_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='anreport',
            field=models.CharField(default='', max_length=8, verbose_name='Annual Reports'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='anreport',
            field=models.CharField(default='', max_length=8, verbose_name='Annual Reports'),
        ),
    ]
