# Generated by Django 3.2.15 on 2023-02-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0009_auto_20230207_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='corptype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Corp Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='corptype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Corp Type'),
        ),
    ]
