# Generated by Django 3.2.15 on 2023-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0010_auto_20230210_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cusname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='cusname',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Customer Name'),
        ),
    ]
