# Generated by Django 3.2.15 on 2023-03-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0011_auto_20230309_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
    ]
