# Generated by Django 3.2.15 on 2023-06-13 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0012_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCards',
            fields=[
                ('idcard', models.BigIntegerField(blank=True, db_index=True)),
                ('idcustomer', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('_cardno_data', encrypted_fields.fields.EncryptedCharField(default='', max_length=50, null=True)),
                ('cardno', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_cardno_data', hash_key='9ddiot5adt6tf7btt16xe', max_length=66, null=True)),
                ('expdate', models.CharField(max_length=45)),
                ('csc', models.CharField(blank=True, max_length=45, null=True)),
                ('zipcode', models.CharField(blank=True, default=' ', max_length=45, null=True)),
                ('status', models.CharField(default='Active', max_length=45)),
                ('last_used', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
