# Generated by Django 3.2.15 on 2023-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0014_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunits',
            name='ifta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='IFTA'),
        ),
        migrations.AddField(
            model_name='units',
            name='ifta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='IFTA'),
        ),
    ]
