# Generated by Django 3.2.15 on 2023-07-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0015_auto_20230712_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='clientpass',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Client Notes'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='clientpass',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Client Notes'),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='type',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('BS', 'BUS'), ('DP', 'DUMP TRUCK'), ('MC', 'MOTORCYCLE'), ('MH', 'MOBILE HOME'), ('PU', 'PICKUP'), ('TK', 'TRUCK'), ('TR', 'TRACTOR'), ('TL', 'TRAILER'), ('TT', 'TOWING'), ('VESSEL', 'VESSEL')], max_length=25, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='units',
            name='type',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('BS', 'BUS'), ('DP', 'DUMP TRUCK'), ('MC', 'MOTORCYCLE'), ('MH', 'MOBILE HOME'), ('PU', 'PICKUP'), ('TK', 'TRUCK'), ('TR', 'TRACTOR'), ('TL', 'TRAILER'), ('TT', 'TOWING'), ('VESSEL', 'VESSEL')], max_length=25, verbose_name='Type'),
        ),
    ]
