# Generated by Django 3.2.15 on 2023-08-17 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0016_auto_20230731_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_log',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.invoices'),
        ),
        migrations.AlterField(
            model_name='email_log',
            name='sending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='email_log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
