# Generated by Django 3.2.15 on 2023-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0017_auto_20230817_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_log',
            name='subject',
            field=models.CharField(default='Invoices', max_length=45),
            preserve_default=False,
        ),
    ]
