# Generated by Django 3.2.15 on 2023-08-22 10:09

import Direct.Apps.Procedure.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0018_email_log_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=Direct.Apps.Procedure.models.exams_directory, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
