# Generated by Django 3.2.15 on 2023-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0019_auto_20230822_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesprojects',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
