# Generated by Django 3.2.15 on 2023-11-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0020_alter_notesprojects_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Florida_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_gvw', models.CharField(max_length=25)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fl_Tag_Price_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_deleted', models.BooleanField(default=False)),
                ('florida_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.florida_tag')),
            ],
        ),
    ]
