# Generated by Django 3.2.15 on 2024-01-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0021_fl_tag_price_month_florida_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='BOIR',
            field=models.BooleanField(default=False, verbose_name='BOIR'),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='BOIR',
            field=models.BooleanField(default=False, verbose_name='BOIR'),
        ),
    ]
