# Generated by Django 3.2.15 on 2024-02-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0022_auto_20240131_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoices',
            fields=[
                ('idinvoice', models.BigIntegerField(blank=True, db_index=True)),
                ('invdate', models.DateField(verbose_name='Inv Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('coments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments')),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], max_length=10, verbose_name='Status')),
                ('cusname', models.CharField(max_length=100, verbose_name='Customer')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('deu', models.FloatField(default=0, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('idcustomer', models.ForeignKey(blank=True, db_column='idcustomer', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Procedure.customers')),
                ('iduser', models.ForeignKey(blank=True, db_column='iduser', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
