# Generated by Django 3.2.15 on 2024-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0023_historicalinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='cdl_state',
            field=models.CharField(default='', max_length=45, verbose_name='STATE CDL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldrivers',
            name='cdl_state',
            field=models.CharField(default='', max_length=45, verbose_name='STATE CDL'),
            preserve_default=False,
        ),
    ]
