# Generated by Django 3.2.15 on 2024-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0024_auto_20240530_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='queries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldrivers',
            name='queries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cdl_state',
            field=models.CharField(max_length=45, verbose_name='State CDL'),
        ),
        migrations.AlterField(
            model_name='historicaldrivers',
            name='cdl_state',
            field=models.CharField(max_length=45, verbose_name='State CDL'),
        ),
    ]
