# Generated by Django 4.2.16 on 2025-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0025_auto_20240606_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcards',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cards', 'verbose_name_plural': 'historical cardss'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomers',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical customers', 'verbose_name_plural': 'historical customerss'},
        ),
        migrations.AlterModelOptions(
            name='historicaldrivers',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical drivers', 'verbose_name_plural': 'historical driverss'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoice_paid',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical invoice_paid', 'verbose_name_plural': 'historical invoice_paids'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoices',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical invoices', 'verbose_name_plural': 'historical invoicess'},
        ),
        migrations.AlterModelOptions(
            name='historicalunits',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical units', 'verbose_name_plural': 'historical unitss'},
        ),
        migrations.AlterField(
            model_name='historicalcards',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldrivers',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoice_paid',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinvoices',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
