# Generated by Django 4.2.16 on 2025-02-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0026_alter_historicalcards_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_det',
            name='idinvoice',
            field=models.ForeignKey(db_column='idinvoice', on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='Procedure.invoices'),
        ),
        migrations.AlterField(
            model_name='invoice_paid',
            name='idinvoice',
            field=models.ForeignKey(db_column='idinvoice', on_delete=django.db.models.deletion.DO_NOTHING, related_name='paids', to='Procedure.invoices'),
        ),
    ]
