# Generated by Django 4.2.16 on 2025-02-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0027_alter_invoice_det_idinvoice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'managed': True},
        ),
    ]
