# Generated by Django 4.2.16 on 2025-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0028_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='commission_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
