# Generated by Django 4.2.16 on 2025-02-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0029_services_commission_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='commission_percentage',
        ),
    ]
