# Generated by Django 4.2.16 on 2025-03-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0030_remove_services_commission_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_det',
            name='code',
            field=models.ForeignKey(db_column='idservice', on_delete=django.db.models.deletion.DO_NOTHING, related_name='code', to='Procedure.services'),
        ),
    ]
