# Generated by Django 4.2.20 on 2026-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0032_historicaluser_historicaltask_historicalstates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallog_invoice_cancel',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='log_invoice_cancel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
