# Generated by Django 4.2.20 on 2026-03-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0033_alter_historicallog_invoice_cancel_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLog_Invoice_cancel',
        ),
    ]
