# Generated by Django 4.2.20 on 2026-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0034_delete_historicallog_invoice_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojects',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Procedure.units'),
        ),
        migrations.AddField(
            model_name='historicalservices',
            name='is_for_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalservices',
            name='should_notify_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='unit_id',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.units'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_for_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='should_notify_client',
            field=models.BooleanField(default=False),
        ),
    ]
