# Generated by Django 4.2.20 on 2026-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0035_historicalprojects_unit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservices',
            name='has_renewal_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='has_renewal_period',
            field=models.BooleanField(default=False),
        ),
    ]
