# Generated by Django 4.2.20 on 2026-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0036_historicalservices_has_renewal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojects',
            name='renewal_period',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='renewal_period',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
