# Generated by Django 4.2.20 on 2026-03-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0037_historicalprojects_renewal_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojects',
            name='renewal_period',
        ),
        migrations.RemoveField(
            model_name='historicalservices',
            name='has_renewal_period',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='renewal_period',
        ),
        migrations.RemoveField(
            model_name='services',
            name='has_renewal_period',
        ),
        migrations.AddField(
            model_name='historicalinvoice_det',
            name='renewal_period',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='historicalservices',
            name='renewal_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice_det',
            name='renewal_period',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='renewal_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
