# Generated by Django 4.2.20 on 2026-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0038_remove_historicalprojects_renewal_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservices',
            name='expiration_type',
            field=models.CharField(choices=[('Internal', 'Internal Calculation'), ('External', 'External Authority')], default='Internal', max_length=10),
        ),
        migrations.AddField(
            model_name='services',
            name='expiration_type',
            field=models.CharField(choices=[('Internal', 'Internal Calculation'), ('External', 'External Authority')], default='Internal', max_length=10),
        ),
    ]
