# Generated by Django 4.2.20 on 2026-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0039_historicalservices_expiration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservices',
            name='expiration_type',
            field=models.CharField(choices=[('Internal', 'Internal Calculation'), ('External', 'External Authority'), ('None', 'No Expiration')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='services',
            name='expiration_type',
            field=models.CharField(choices=[('Internal', 'Internal Calculation'), ('External', 'External Authority'), ('None', 'No Expiration')], default='None', max_length=10),
        ),
    ]
