# Generated by Django 3.2.15 on 2022-10-18 21:12

import Direct.Apps.Attendanceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('clock_in_at', models.TimeField()),
                ('lunch_in_at', models.TimeField(blank=True, null=True)),
                ('lunch_out_at', models.TimeField(blank=True, null=True)),
                ('clock_out_at', models.TimeField(blank=True, null=True)),
                ('hours', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('surnames', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Direct.Apps.Attendanceapp.models.users_directory)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(choices=[('America/New_York', 'America/New York'), ('America/Guayaquil', 'America/Guayaquil')], default='America/New_York', max_length=32, verbose_name='Time Zone')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
