# Generated by Django 4.2.20 on 2025-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0003_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
