# Generated by Django 4.2.16 on 2025-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
