# Generated by Django 4.2.20 on 2026-03-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0006_alter_attendance_date_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_in_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_out_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
