# Generated by Django 4.2.16 on 2024-12-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Procedure', '0026_alter_historicalcards_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('current_drivers', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('drug_testing_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alcohol_testing_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_RandomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('test_substances', models.BooleanField(default=False)),
                ('test_alcohol', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.customers')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.drivers')),
                ('random_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Consortium.randomlist')),
                ('test_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.exams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
