# Generated by Django 4.2.16 on 2024-12-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consortium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomlist',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
