# Generated by Django 4.2.16 on 2024-12-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consortium', '0002_randomlist_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomlist',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
