# Generated by Django 4.2.16 on 2024-12-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0026_alter_historicalcards_options_and_more'),
        ('Consortium', '0003_randomlist_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_randomlist',
            name='comment',
        ),
        migrations.AddField(
            model_name='detail_randomlist',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.notes'),
        ),
    ]
