# Generated by Django 4.2.16 on 2024-12-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0026_alter_historicalcards_options_and_more'),
        ('Consortium', '0004_remove_detail_randomlist_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_randomlist',
            name='note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.notes'),
        ),
        migrations.AlterField(
            model_name='detail_randomlist',
            name='test_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.exams'),
        ),
    ]
