# Generated by Django 4.2.16 on 2025-01-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Consortium', '0005_alter_detail_randomlist_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_randomlist',
            name='note',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('detail_random_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Consortium.detail_randomlist')),
            ],
        ),
    ]
