# Generated by Django 4.2.16 on 2025-02-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consortium', '0006_remove_detail_randomlist_note_comments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail_randomlist',
            table='detail_random_list',
        ),
    ]
