# Generated by Django 4.2.16 on 2025-02-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consortium', '0007_alter_detail_randomlist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detail_randomlist',
            table=None,
        ),
    ]
