# Generated by Django 4.2.16 on 2025-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consortium', '0008_alter_detail_randomlist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_randomlist',
            name='test_file',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
