# Generated by Django 4.2.16 on 2025-03-19 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Consortium', '0009_alter_detail_randomlist_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='detail_random_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consortium.detail_randomlist'),
        ),
        migrations.AlterField(
            model_name='detail_randomlist',
            name='random_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consortium.randomlist'),
        ),
        migrations.AlterField(
            model_name='randomlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
