# Generated by Django 4.2.20 on 2025-08-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procedure', '0031_alter_invoice_det_code'),
        ('Consortium', '0010_alter_comments_detail_random_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_randomlist',
            name='test_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Procedure.exams'),
        ),
    ]
